name: Next.js Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x] # Vous pouvez ajouter d'autres versions si nécessaire

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Generate Prisma Client
      run: npx prisma generate
      
    - name: Build
      run: npm run build
      
    - name: Lint
      run: npm run lint || echo "No linting configured"
      
    # Ajoutez des tests ou d'autres étapes si nécessaire
    # - name: Run tests
    #   run: npm test
